# Generated by Django 4.1.2 on 2022-10-09 10:19

from django.db import migrations


def populate_airports(apps, schema_editor):
    Airport = apps.get_model('airport', 'Airport')
    Airport.objects.create(id=1, name='Sheremetyevo', iata="SVO", city_id=1)
    Airport.objects.create(id=2, name='Nizhnevartovsk', iata="NJC", city_id=2)


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0001_initial"),
        ("city", "0002_auto_20221009_1015"),
    ]

    operations = [
        migrations.RunPython(populate_airports),
    ]
