# Generated by Django 4.1.2 on 2022-10-09 10:15

from django.db import migrations


def populate_cities(apps, schema_editor):
    City = apps.get_model('city', 'City')
    City.objects.create(id=1, name='Moscow')
    City.objects.create(id=2, name='Nizhnevartovsk')


class Migration(migrations.Migration):

    dependencies = [
        ("city", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(populate_cities),
    ]
