# Generated by Django 4.1.6 on 2023-02-11 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("airport", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlightAirport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                ("time", models.TimeField()),
                (
                    "airport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="airport.airport",
                    ),
                ),
            ],
            options={
                "db_table": "flight_airport",
            },
        ),
        migrations.CreateModel(
            name="Flight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=7)),
                ("cost", models.FloatField()),
                ("availability", models.IntegerField()),
                ("date", models.DateField()),
                (
                    "arrival",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="flight_arrival",
                        to="flight.flightairport",
                    ),
                ),
                (
                    "departure",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="flight_departure",
                        to="flight.flightairport",
                    ),
                ),
            ],
            options={
                "db_table": "flight",
            },
        ),
    ]
