# Generated by Django 4.1.6 on 2023-02-12 18:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("airport", "0001_initial"),
        ("flight", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FlightAirport",
            new_name="FlightJuncture",
        ),
        migrations.AlterModelTable(
            name="flightjuncture",
            table="flight_juncture",
        ),
    ]
