# Generated by Django 4.1.1 on 2022-09-28 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("flight", "0001_initial"),
        ("flight_airport", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="flight",
            name="arrival",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="flight_arrival",
                to="flight_airport.flightairport",
            ),
        ),
        migrations.AddField(
            model_name="flight",
            name="departure",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="flight_departure",
                to="flight_airport.flightairport",
            ),
        ),
    ]
