# Generated by Django 4.1.1 on 2022-10-01 04:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flight", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="flight",
            name="date",
            field=models.DateField(default=datetime.date(2022, 10, 1)),
            preserve_default=False,
        ),
    ]
