# Generated by Django 4.1.2 on 2022-10-09 10:26

from django.db import migrations


def populate_flights(apps, schema_editor):
    Flight = apps.get_model('flight', 'Flight')
    Flight.objects.create(id=1, code="SU123", departure_id=1, arrival_id=2, cost=8000.0, availability=100, date="2022-10-09")
    Flight.objects.create(id=2, code="SU456", departure_id=3, arrival_id=4, cost=8000.0, availability=100, date="2022-10-09")

class Migration(migrations.Migration):

    dependencies = [
        ("flight", "0003_flight_date"),
        ("flight_airport", "0002_auto_20221009_1019"),
    ]

    operations = [
        migrations.RunPython(populate_flights),
    ]
