# Generated by Django 4.1.1 on 2022-10-01 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("flight", "0003_flight_date"),
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="flight_back",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="booking_back",
                to="flight.flight",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="flight_from",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="booking_from",
                to="flight.flight",
            ),
            preserve_default=False,
        ),
    ]
