# Generated by Django 4.1.1 on 2022-09-28 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("airport", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlightAirport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                ("time", models.TimeField()),
                (
                    "airport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="airport.airport",
                    ),
                ),
            ],
            options={
                "db_table": "flight_airport",
            },
        ),
    ]
