# Generated by Django 4.1.2 on 2022-10-09 10:19

from django.db import migrations


def populate_flight_airports(apps, schema_editor):
    FlightAirport = apps.get_model('flight_airport', 'FlightAirport')
    FlightAirport.objects.create(id=1, airport_id=1, date=None, time="10:00:00")
    FlightAirport.objects.create(id=2, airport_id=2, date=None, time="14:00:00")
    FlightAirport.objects.create(id=3, airport_id=2, date=None, time="18:00:00")
    FlightAirport.objects.create(id=4, airport_id=1, date=None, time="22:00:00")


class Migration(migrations.Migration):

    dependencies = [
        ("flight_airport", "0001_initial"),
        ("airport", "0002_auto_20221009_1019"),
    ]

    operations = [
        migrations.RunPython(populate_flight_airports),
    ]
